rancher-sandbox/hypper

- .github/workflows/golangci-lint.yml
For now, we always run the workflow, regardless of branch and reviews. This
means that PRs could change the workflow code and have access to Github secrets
or infrastructure (clusters, etc). But we don't have any of those yet, nor we
will have for a bit.
For an example of a correct run that fails tests, see https://github.com/viccuad/hypper/pull/1
(where golangci-lint is run on an existing branch, instead of the empty main branch).
Closes #6.
> Add GH Actions workflow for golangci-lint

- .github/workflows/ci.yml
- .gitignore
- Makefile
- go.mod
- scripts/coverage.sh
This adds a Makefile for the project, and a GH Actions workflow with steps for building, testing and showing coverage (for MacOS, Windows and Ubuntu).
Closes #5.
> Add GH Actions CI for building and testing

- .github/workflows/ci.yml
We should test at least the maintained go versions so we can check
if something fails on any of those versions
> Enable matrix for go version testing

- .github/workflows/ci.yml
There is no need to look further than the specific cache for
the combination of os+go.sum. Either we have a hit and use the
full cache or the hash of go.sum has changed and we need a new
cache for the build. Reusing a generic cache is not useful and
can cause problems
> Drop restore key from CI cache

- cmd/hypper/hypper.go
- cmd/hypper/install.go
- go.mod
- go.sum
- pkg/cli/environment.go
- pkg/cli/environment_test.go
- pkg/eyecandy/colors.go
- pkg/eyecandy/emoji.go
- pkg/eyecandy/emoji_test.go
This PR adds support for outputting emojis to the cli.
It uses the common `:emoji:` notation known from popular messaging clients like element.
examples:
`:+1: `-> :+1: 
`:pizza:` -> :pizza: 
`:100:` -> :100: ....
Closes #2
> Emojis :pizza:

- cmd/hypper/root_test.go
This PR adds a test for running the command with an unknown subcommand.
Closes #7
> Add missing test for unknown subcommand

- .github/workflows/golangci-lint.yml
Note, I noticed the lint process was taking more than 29s and timing out. golangci-lint defaults to a 1m0s timeout but that was not happening. Helm takes about 45s to lint in CircleCI. So, I increased the lint timeout period.
> Updating golangci-lint to 1.36

- cmd/hypper/hypper.go
- cmd/hypper/hypper_test.go
- cmd/hypper/install.go
- cmd/hypper/root.go
- cmd/hypper/uninstall.go
- go.mod
- go.sum
The github.com/mattfarina/log-go package moved to its new home
in an organization. This change uses it in its new home.
> moving to new log-go home

- Makefile
This PR closes #36
It outputs `bin/hypper.exe` instead of `bin/hypper` when running make on windows.
> add file extension for windows

- CONTRIBUTING.md
The DCO is copied verbatim from Helm.
A Github App can be enabled to provide DCO gating for the PRs with https://github.com/apps/dco#usage (click "configure").
I would be happy enabling it once this is merged.
> Add CONTRIBUTING.md with DCO

- cmd/hypper/hypper.go
- cmd/hypper/hypper_test.go
- cmd/hypper/install.go
- cmd/hypper/list.go
- cmd/hypper/root.go
- cmd/hypper/uninstall.go
- pkg/README.md
- pkg/action/action.go
- pkg/action/install.go
- pkg/action/list.go
- pkg/action/uninstall.go
Provide a manageable API to __hypper/pkg/action__ by embedding __helm/pkg/action__ types inside of it. Use Golang composition and embedded fields for doing so.
This allows us to expand the action package slowly from Helm's, while presenting a Hypper API that can be consumed externally.
See commit comments for expanded explanations.
Upsides:
- The refactor allows us to keep the same structure as Helm (for easy upstreaming).
- Allows us to extend the code incrementally.
- Allows us to provide the __hypper/pkg/*__ for consumption.
Downsides:
- We need to disable checking for composites in `go vet`. Given that we don't compose any other types, and the types that we compose (__hypper/pkg/action__ and __hypper/pkg/*__ in the future) are under our control, I believe the trade-off really pays …
> Use Golang composition to extend helm/pkg/action in hypper/pkg/action

- .github/workflows/ci.yml
- Makefile
- Run golangci-lint as part of `make test`. Just as Helm does, so we don't forget to run it when developing. 
Adapt GH actions to not run golangci-lint twice.
- Add `make gen-test-golden` target, analogous to Helm's.
> Run golangci-lint on `make test`, add `make gen-test-golden`

- cmd/hypper/root.go
- cmd/hypper/status.go
- cmd/hypper/status_test.go
- cmd/hypper/testdata/output/status-with-desc.txt
- cmd/hypper/testdata/output/status-with-notes.txt
- cmd/hypper/testdata/output/status-with-test-suite.txt
- cmd/hypper/testdata/output/status.json
- cmd/hypper/testdata/output/status.txt
- pkg/action/status.go
Basically lifted from the helm status command with minor changes:
- Uses log-go for output
- Removes tests for auto completion as we dont have that yet
Fixes: #52 
> Add status command

- cmd/hypper/testdata/output/uninstall-no-args.txt
- cmd/hypper/uninstall.go
This mimics Helm's UI by providing `hypper uninstall/delete/del/un` and
suggesting the `uninstall` command in case of asking for `remove/rm`.
Signed-off-by: Víctor Cuadrado Juan <vcuadradojuan@suse.de>
> Add aliases and suggests to uninstall command

- .github/workflows/golangci-lint.yml
Noticed timeout in lint jobs. Helm had to increase as well.
> Increasing lint timeout

- pkg/action/upgrade.go
license checker was failing due merging 2 prs at the same
time, one that dixed all license headers and the other
that introduced this file, so the license checker was
green until now :D
> Add missing action/upgrade.go license

- cmd/hypper/install.go
When mimicking the addInstallFlags from Install we
missed the values flags and the chartoptions flags
Fixes: #68 
> Add missing flag to Install

- cmd/hypper/uninstall.go
- pkg/action/uninstall.go
We are missing reading from the chart annotations as well,
or maybe thats not gonna be implemented?
We are missing this piece to be able to clean up the resources properly but probably missing obtaining the namespace from annotattions which is quite bigger....and would probably benefit from extraction some generic methods...
Partial fix: #77 
> Set the client namespace on uninstall

- cmd/hypper/install.go
- cmd/hypper/install_test.go
- cmd/hypper/testdata/output/install-no-name-or-annot.txt
- pkg/action/install.go
- pkg/action/install_test.go
This PR removes the `--generate-name` flag, if now chart name is provided (either through annotations or cli) it will use the name from the `Chart.yaml` out of the chart itself.
> Deterministic names

- cmd/hypper/hypper_test.go
- cmd/hypper/testdata/output/upgrade-with-install-release-name.txt
- cmd/hypper/testdata/output/upgrade-with-release-name.txt
- cmd/hypper/upgrade.go
- cmd/hypper/upgrade_test.go
- pkg/action/upgrade.go
- pkg/action/upgrade_test.go
Namespace was not being set via annotations properly
for the upgrade command nor the install command called
from the upgrade
Fixes: #73 
> Fix namespace set on upgrade command

- Makefile
This is to fix a case in which we build hypper on windows
based of the windows golang binary who is aware of the full
windows path, from a POSIX env like cygwin which is unaware
that is running on windows and uses a "fake" disk paths.
The result is that building the output ends up in the disk
drive that go runs out from + output path while rm tries to
clean the "fake" output path only
By using the relative path for building the binary we
avoid any mangling issues.
As a side effect this also removes the binary quotes that
were added for no discernible reason and while they didnt
affect anything AFAIK, they looked terrible.
Fixes: #41 
> Use relative path for bin dir in Makefile

- .github/workflows/releaser.yml
- .goreleaser.yml
Uses the goreleaser action to build and
provide hypper builds for macos, linux, windows
in an automated fashion
Fixes: #95 
> use goreleaser to provide hypper builds

- .goreleaser.yml
Due to github merge defaults we usually get this
extra messages on the commit history of the repo.
They are kind of extra as they provide no info in
the changelog, so lets just exclude those from
appearing in the changelog.
> Drop "Merge pull request" from changelog

- Makefile
If we dont have a tag for the current commit
the makefile will set the version to an empty
value. While that is kind of ok, as there is no
version attached to that, I think setting it
to last_tag+version+short_commit is nicer
With the patch we also allow to use a GIT_TAG
env var already, useful to build specific or
custom versions
> Enhance version set

- cmd/hypper/install.go
- cmd/hypper/upgrade.go
- pkg/action/dependency_shared_test.go
- pkg/action/install.go
- pkg/action/install_test.go
- pkg/action/upgrade.go
- pkg/action/upgrade_test.go
- pkg/action/utils.go
As both install and upgrade are using the action.SetNamespace
method, this extracts that method into a different file and
decouples it from the action so its easier to share and reuse
At the same time expands the method so it checks for the
NamespaceFromFlag and sets the client.Config storage
driver to the same namespace as the client in one go,
so we dont have to call multiple places for a namespace change
> Introduce common methods for setNamespace and Name

- pkg/action/utils.go
- pkg/action/utils_test.go
This change adds a default switch to SetNamespace to handle the
situation of a type it does not know how to deal with. This will
catch a use of the function in a situation it does not know how
to deal with.
> Catch unknown type in SetNamespace

- .github/workflows/docs-book.yml
- .gitignore
- book.toml
- docs/SUMMARY.md
- docs/user/howto/README.md
- docs/user/tutorials/installing.md
This uses mdBook to generate a book with all the
docs based of the SUMMARY.md file and with the book.toml
configuration.
Then it builds the book with the docs unders docs in the book/
directory and pushes that to the gh-pages branch which then is
published by github pages, making the docs available
> Add docs generation to workflows

- cmd/hypper/root.go
- cmd/hypper/search.go
- cmd/hypper/search_test.go
- cmd/hypper/testdata/hypperhome/hypper/repositories.yaml
- cmd/hypper/testdata/hypperhome/hypper/repository/test-name-index.yaml
- cmd/hypper/testdata/hypperhome/hypper/repository/testing-index.yaml
- cmd/hypper/testdata/output/search-constraint-single.txt
- cmd/hypper/testdata/output/search-constraint.txt
- cmd/hypper/testdata/output/search-multiple-devel-release.txt
- cmd/hypper/testdata/output/search-multiple-stable-release.txt
- cmd/hypper/testdata/output/search-multiple-versions-constraints.txt
- cmd/hypper/testdata/output/search-multiple-versions.txt
- cmd/hypper/testdata/output/search-not-found.txt
- cmd/hypper/testdata/output/search-output-json.txt
- cmd/hypper/testdata/output/search-output-yaml.txt
- cmd/hypper/testdata/output/search-regex.txt
- cmd/hypper/testdata/output/search-versions-constraint.txt
- cmd/hypper/upgrade_test.go
- docs/user/howto/search.md
- go.mod
- pkg/search/index.go
- pkg/search/index_test.go
- pkg/search/search.go
Adds the helm repo search command to hypper as just hypper search
Under helm you can search on the repos or on their own hub. This
patch only implements the repo search as seems the most useful
and bringing the hub requires a lot of code
This patch also extracts the search code into a new pkg as under
helm the search code is mostly crammed under cmd which means you cannot
use it anywhere, meanwhile this code can be reused by third party
clients to implement their own search frontend or automate it.
Fixes: #78 
> Add search command

- cmd/hypper/root.go
- pkg/cli/environment.go
We were filling all the helm settings before parsing the
flags, which means that anything using those helm settings for
any action would just get the default values instead of any cli
values.
This fixes the issue by creating a fill function and calling
it after the flags have been parsed, thus making sure that those
flags are properly propagated.
Otherwise the envsettings behavior its the same as it was before
as the default hypoper values are propagated to helm settings on
Envsettings construct
> Fix helm settings for flags

- docs/SUMMARY.md
- docs/reference-guides.md
Rendered: https://github.com/rancher-sandbox/hypper/blob/link-doc-pages/docs/SUMMARY.md
> docs: Link new doc pages, add reference-guides.md

- cmd/hypper/docs.go
- cmd/hypper/docs_test.go
- cmd/hypper/root.go
- go.sum
This is lifted from Helm's `cmd/helm/docs.go`.
This will allow us to automate creation of cli docs, to put on the docs page.
Example:
```shell
$ mkdir docs/user/cli
$ hypper docs -dir docs/user/cli
$ tree docs/user/cli
docs/user/cli
├── hypper_install.md
├── hypper_lint.md
├── hypper_list.md
├── hypper.md
├── hypper_repo_add.md
├── hypper_repo_index.md
├── hypper_repo_list.md
├── hypper_repo.md
├── hypper_repo_remove.md
├── hypper_repo_update.md
├── hypper_search.md
├── hypper_search_repo.md
├── hypper_shared-dep_list.md
├── hypper_shared-dep.md
├── hypper_status.md
├── hypper_uninstall.md
├── hypper_upgrade.md
└── hypper_version.md
```
> feat: Add `hypper docs` command, to generate markdown/man/bash command docs

- cmd/hypper/install.go
- cmd/hypper/install_test.go
- cmd/hypper/testdata/output/install-with-shared-deps.txt
- cmd/hypper/testdata/testcharts/shared-deps/Chart.yaml
- cmd/hypper/testdata/testcharts/shared-deps/README.md
- cmd/hypper/testdata/testcharts/shared-deps/templates/empty.yaml
- cmd/hypper/testdata/testcharts/shared-deps/values.yaml
- cmd/hypper/upgrade.go
- go.mod
- go.sum
- pkg/action/action_test.go
- pkg/action/dependency_shared.go
- pkg/action/install.go
- pkg/action/install_test.go
- pkg/action/testdata/charts/hypper-annot/Chart.yaml
- pkg/action/testdata/output/install-correctly-shared-deps.txt
- pkg/action/testdata/output/install-malformed-shared-deps.txt
- pkg/action/testdata/output/install-no-shared-deps.txt
- pkg/action/testdata/output/install-shared-dep-installed.txt
- pkg/action/testdata/output/shared-deps-some-deps.txt
This PR adds functionality to install shared-deps of a chart when calling `hypper install CHART`.
This can be skipped with `hypper install CHART --no-shared-deps`.
For now, shared-deps get installed with default values.yaml (they get an empty Values), and there's
no checking that the dependencies satisfy a specific version.
For that, it adds 2 methods to `pkg/action/install.go`: `InstallAddSharedDeps()`, `InstallSharedDep()`.
This implementation introduces duplicated code between `cmd/hypper/install.go.Run()` and
`pkg/action/install.go.{InstallAddSharedDeps(),InstallSharedDep()}.`
In the future,  we can deduplicate the code for loading charts, checking for chart deprecation, and
matching chart versions. I suppose those would go into `pkg/action/install` or `pkg/chart`, or the like.
The …
> feat: Add initial functionality to install shared deps of a chart

- .github/workflows/docs-book.yml
Because now we are using the linkchecker output for testing
the docs link validation, mdbook finds 2 different outputs
and tries to ensure that each output gets its own directory
thus now we have to set the specific html dir where the
output is dumped on
> Set proper dir for publishing docs

- pkg/action/install.go
- pkg/action/install_test.go
- pkg/action/testdata/charts/hypper-annot/Chart.yaml
- pkg/action/testdata/charts/shared-dep/Chart.yaml
- pkg/action/testdata/charts/shared-dep/README.md
- pkg/action/testdata/charts/shared-dep/templates/empty.yaml
- pkg/action/testdata/charts/shared-dep/values.yaml
- pkg/action/testdata/output/shared-deps-some-deps.txt
Correctly install shared-deps in their own specified namespaces.
> fix: Honour annotations' namespaces of shared-deps

- pkg/cli/environment.go
- pkg/cli/environment_test.go
Remove helm settings as composite to avoid propagation of
new fields into our settings automatically
Doesnt really matter as we are overwritting all fields
with our own values
Adds a checker to check that we are not missing any fields
> Check for field differences in our settings

- cmd/hypper/search.go
- cmd/hypper/search_test.go
- cmd/hypper/testdata/hypperhome/hypper/repository/testing-index.yaml
- cmd/hypper/testdata/output/search-hypper-annotation-regexp.txt
- cmd/hypper/testdata/output/search-hypper-annotation-version-regexp.txt
- cmd/hypper/testdata/output/search-hypper-annotation-version.txt
- cmd/hypper/testdata/output/search-hypper-annotation.txt
- cmd/hypper/testdata/output/search-hypper-latest.txt
- docs/user/howto/searchannotations.md
- pkg/search/doc.go
- pkg/search/index.go
- pkg/search/search.go
Allows to add filtering by annotations by passing the -a flag and the
annotation in the format "KEY=VALUE"
So you can search like this:
`hypper search repo -a "catalog.cattle.io/certified=rancher"`
And it will only show charts that have that exact annotation.
Requires #113 
> Add filtering by annotations on search

- scripts/get-hypper
This PR fixes the following issue with shellcheck:
```
==> Checking shell scripts <==
shellcheck ./scripts/*
In ./scripts/get-hypper line 91:
if [ "x$DESIRED_VERSION" == "x" ]; then
^-----------------^ SC2268: Avoid x-prefix in comparisons as it no longer serves a purpose.
Did you mean: 
if [ "$DESIRED_VERSION" == "" ]; then
For more information:
https://www.shellcheck.net/wiki/SC2268 -- Avoid x-prefix in comparisons as ...
make: *** [Makefile:92: shellcheck] Error 1
```
> Fix get_hypper after shellcheck update

- docs/user/howto/expandcharthypper.md
- docs/user/howto/lintchart.md
- docs/user/howto/shared-deps.md
- docs/user/tutorials/quickstart.md
Update docs with current CLI output and optional-deps examples for
`hypper install`, `hypper lint`, and `hypper shared-deps list`.
Comes together with https://github.com/rancher-sandbox/hypper-charts/pull/5. 
Signed-off-by: Víctor Cuadrado Juan <vcuadradojuan@suse.de>
> docs: Update cli output and add optional-dep examples

- cmd/hypper/hypper.go
- cmd/hypper/hypper_test.go
- cmd/hypper/root.go
- cmd/hypper/testdata/output/install-incorrect-flag-optional-deps.txt
- cmd/hypper/testdata/output/install-no-chart.txt
- cmd/hypper/testdata/output/install-with-shared-deps-out-of-range.txt
- cmd/hypper/testdata/output/lint-chart-with-bad-subcharts-with-subcharts-windows.txt
- cmd/hypper/testdata/output/lint-chart-with-bad-subcharts-with-subcharts.txt
- cmd/hypper/testdata/output/lint-chart-with-bad-subcharts.txt
- cmd/hypper/testdata/output/shared-deps-list-no-chart-linux.txt
- cmd/hypper/testdata/output/shared-deps-list-no-chart-windows.txt
- cmd/hypper/testdata/output/uninstall-no-args.txt
- cmd/hypper/testdata/output/upgrade-with-bad-dependencies.txt
- cmd/hypper/testdata/output/upgrade-with-bad-or-missing-existing-release.txt
- cmd/hypper/testdata/output/upgrade-with-missing-dependencies.txt
- cmd/hypper/testdata/output/upgrade-with-pending-install.txt
- pkg/action/lint.go
Configure cobra to not print errors, we will print the floated errors ourselves.
Fix test setup to funnel all errors to the same buffer, and print them to goldenfiles.
E.g: See that all printed errors now start with `ERROR:` (log-go, with colors, etc) and not `Error: ` (cobra).
Also, print error in pkg/ when one cannot open `Chart.yaml` in `hypper lint`.
Closes: https://github.com/rancher-sandbox/hypper/issues/155
> Configure CLI to print errors using log-go

- cmd/hypper/install.go
- cmd/hypper/install_test.go
- cmd/hypper/testdata/output/install-no-create-namespace.txt
- cmd/hypper/upgrade.go
- docs/user/howto/shared-deps.md
- docs/user/tutorials/quickstart.md
- pkg/action/install.go
Default to creating ns in `hypper install` and `hypper upgrade`.
Add new flag `--no-create-namespace`, defaults to false, so namespaces are created by default.
Drop old flag `--create-namespace`.
Update present tests and docs.
Closes: https://github.com/rancher-sandbox/hypper/issues/162
> feat: Default to creating namespaces

- cmd/hypper/testdata/output/install-dry-run-with-all-optional-deps.txt
- cmd/hypper/testdata/output/install-hypper-annot.txt
- cmd/hypper/testdata/output/install-name-ns-args.txt
- cmd/hypper/testdata/output/install-no-create-namespace.txt
- cmd/hypper/testdata/output/install-skip-all-optional-deps.txt
- cmd/hypper/testdata/output/install-with-all-optional-deps.txt
- cmd/hypper/testdata/output/install-with-shared-deps.txt
- internal/solver/solver.go
- internal/solver/testdata/output/format-sat-install1-table.txt
- internal/solver/testdata/output/format-sat-upgrade-table.txt
- pkg/action/install.go
- pkg/action/testdata/output/install-correctly-optional-shared-deps.txt
- pkg/action/testdata/output/install-correctly-shared-deps-looped-repo-file.txt
- pkg/action/testdata/output/install-correctly-shared-deps-repo-file.txt
- pkg/action/testdata/output/install-correctly-shared-deps.txt
- pkg/action/testdata/output/install-shared-deps-dry-run.txt
- pkg/action/testdata/output/install-shared-deps-with-ns-from-flag.txt
- pkg/action/testdata/output/install-shared-deps-without-annotations.txt
This PR adds an ASCII tree of charts to be installed, when doing `hypper install`. Example:
```console
$ hypper install ./local-hypper-charts/charts/demo --dry-run        
The following charts are going to be installed:
demo v0.2.0
├─ demo-a v0.1.0
├─ demo-b v0.2.0
│  └─ demo-c v0.1.0
└─ demo-d v0.2.0
🛳  Installing chart "demo-a" as "demo-a" in namespace "demo-a"…
🛳  Installing chart "demo-c" as "demo-c" in namespace "demo-c"…
🛳  Installing chart "demo-b" as "demo-b" in namespace "demo-b"…
🛳  Installing chart "demo-d" as "demo-d" in namespace "demo-d"…
🛳  Installing chart "demo" as "demoit" in namespace "demo"…
👏 Done!
```
(in console the ASCII pipes are continuous, GH markdown makes a mess).
Closes https://github.com/rancher-sandbox/hypper/issues/178.
> Print ASCII tree on `hypper install`

- pkg/action/install.go
When f19146a15ac4c750efc2e05ac988b7c04bc598d6 landed the repo
location was switched for the registry location. The registry is
used with OCI. This was likely an accidental autocomplete name
change. It caused the solver to be unaware of the repos and charts
within them. Changing to the right location fixes the issue.
Closes #181
> Fixing db not looking at repos

- cmd/hypper/install.go
- pkg/action/world.go
The situation is that you have A > B > C. The repo containing B and
C are missing. The code to load files was loading B but not C.
The solver would silently skip C and just install A and B.
For security reasons, we should not install charts from repos
when the repo has not been explicitly added. This is out other
system package managers work and is security guidance out of
reviews of Helm.
The solution here was to look for local files and then throw
an error if a depenency isn't a local file or in a repo.
Closes #182
> Fixing issue where charts in repos not erroring on dep issues
