.github/workflows/golangci-lint.yml

Enables verbose so we can analyze any failures

Enable verbose output

---

cmd/hypper/hypper.go
cmd/hypper/hypper_test.go
cmd/hypper/install.go
cmd/hypper/root.go
cmd/hypper/testdata/output/uninstall-keep-history.txt
cmd/hypper/testdata/output/uninstall-multiple.txt
cmd/hypper/testdata/output/uninstall-no-args.txt
cmd/hypper/testdata/output/uninstall-no-hooks.txt
cmd/hypper/testdata/output/uninstall-timeout.txt
cmd/hypper/testdata/output/uninstall.txt
cmd/hypper/uninstall.go
cmd/hypper/uninstall_test.go
go.mod
go.sum
internal/test/test.go
pkg/cli/environment.go
pkg/cli/environment_test.go

This PR adds the uninstall command to hypper for uninstalling helm deployments.

Add uninstall command

---

cmd/hypper/testdata/output/uninstall-no-args.txt
go.mod
go.sum
pkg/cli/environment.go

Also removing the -v flag that can conflict with k8s internal logging

Updating log setup

---

pkg/action/list.go

Noticed by @Itxaka on https://github.com/rancher-sandbox/hypper/pull/53#discussion_r585370228.

Use our action/Configuration instead of Helm's in pkg/action/list.go

---

internal/test/ensure/ensure.go

Instead of using helm for the pattern

Create temp dir with hypper pattern

---

go.mod
pkg/action/action.go
pkg/action/lazyclient.go

fix(storage): Fixing namespace of install storage

---

.github/workflows/ci.yml

Signed-off-by: Víctor Cuadrado Juan <vcuadradojuan@suse.de>

Save GHA job results as artifacts, for 20 days

---

docs/user/tutorials/installing.md
docs/user/tutorials/quickstart.md

Based on https://github.com/helm/helm-www/tree/master/content/en/docs/intro.
Partially implements https://github.com/rancher-sandbox/hypper/issues/61.

Add docs/user/tutorials/{installing,quickstart}.md

---

cmd/hypper/version.go
internal/version/version.go

Now watch my embarrassment for getting a print
into the main branch, fade by reading this commit
message in haiku format.
Enjoy.
Left a print statement.
Passed the tests without issues?
Removed it, all good.

Remove print statement from version

---

.github/workflows/get-hypper.yml
.github/workflows/shellcheck.yml
Makefile
scripts/get-hypper
scripts/license_check.sh

Adds bash installer based off the helm installer with
some simplifications
Fixes: #94
Blocked by: https://github.com/rancher-sandbox/hypper/pull/96

Add sh installer

---

.github/workflows/shellcheck.yml

There is no point in running it all the time if
the scripts dont change

Only run shellcheck if scripts have changed

---

docs/user/tutorials/installing.md

Expand on the install tutorial

---

pkg/action/doc.go
pkg/action/utils.go
pkg/cli/environment.go
pkg/eyecandy/emoji.go
pkg/hypperpath/home.go
pkg/repo/doc.go

So it expands the current reference docs
Fixes #83 maybe?

Add more reference comments

---

docs/user/howto/expandcharthypper.md

Add howto on How to expand a chart with hypper

---

pkg/action/doc.go
pkg/eyecandy/emoji.go

Fix 2 small vet issues

---

.github/workflows/docs-book.yml
book.toml
docs/user/howto/lintchart.md
docs/user/tutorials/installing.md
docs/user/tutorials/quickstart.md

Signed-off-by: Víctor Cuadrado Juan <vcuadradojuan@suse.de>

feat: Run mdbook test in docs-book gha workflow

---

README.md

: >.
[Rendered readme](https://github.com/rancher-sandbox/hypper/pull/126/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

feat: Add CI and doc book badges to README.md

---

docs/SUMMARY.md
docs/user/howto/expandcharthypper.md
docs/user/howto/lintchart.md
docs/user/howto/search.md
docs/user/howto/shared-deps.md
docs/user/tutorials/installing.md
docs/user/tutorials/quickstart.md

[rendered](https://github.com/rancher-sandbox/hypper/pull/131/commits/0609bdd490480e139558e27e8a8b3d5f98da3064?short_path=bddc36d#diff-bddc36daab1e3775b8187107b112740c8bb312e1b068cbd66c81349a652d9945).
Closes: https://github.com/rancher-sandbox/hypper/issues/129.

docs: Add how-to on shared-deps

---

docs/shared-dependencies.md
docs/user/howto/pull.md
docs/user/howto/search.md
docs/user/howto/shared-deps.md
docs/user/tutorials/quickstart.md

Closes: https://github.com/rancher-sandbox/hypper/issues/140

docs: Use hypper-charts repo for examples

---

CONTRIBUTING.md
cmd/hypper/install.go
cmd/hypper/testdata/output/install-create-namespace.txt
cmd/hypper/testdata/output/install-fallback-annot.txt
cmd/hypper/testdata/output/install-hypper-annot.txt
cmd/hypper/testdata/output/install-name-ns-args.txt
cmd/hypper/testdata/output/install-no-name-or-annot.txt
cmd/hypper/testdata/output/install-with-shared-deps.txt
cmd/hypper/testdata/output/uninstall-keep-history.txt
cmd/hypper/testdata/output/uninstall-multiple.txt
cmd/hypper/testdata/output/uninstall-no-hooks.txt
cmd/hypper/testdata/output/uninstall-timeout.txt
cmd/hypper/testdata/output/uninstall.txt
cmd/hypper/testdata/output/upgrade-with-install-release-name.txt
cmd/hypper/testdata/output/upgrade-with-install-timeout.txt
cmd/hypper/testdata/output/upgrade-with-install.txt
cmd/hypper/testdata/output/upgrade-with-release-name.txt
cmd/hypper/testdata/output/upgrade-with-reset-values.txt
cmd/hypper/testdata/output/upgrade-with-reset-values2.txt
cmd/hypper/testdata/output/upgrade-with-timeout.txt
cmd/hypper/testdata/output/upgrade-with-wait-for-jobs.txt
cmd/hypper/testdata/output/upgrade-with-wait.txt
cmd/hypper/testdata/output/upgrade.txt
cmd/hypper/uninstall.go
cmd/hypper/upgrade.go
pkg/action/install.go
pkg/action/testdata/output/install-correctly-shared-deps.txt
pkg/action/testdata/output/install-malformed-shared-deps.txt
pkg/action/testdata/output/install-shared-dep-installed.txt

This PR adds an emoji style guide to `CONTRIBUTING.md` and adapts the guide to the existing code.

Emoji style guide

---

pkg/lint/lint_test.go
pkg/lint/rules/annotations.go

We were not parsing the yaml and semver for optional shared-deps.

fix: Lint optional shared-deps, and show errors

---

docs/sat-solver.md

Rendered document: https://github.com/rancher-sandbox/hypper/blob/sat-solver/docs/sat-solver.md.
Rendering Latex in GH is a mess.. Rendered them via svgs using this [hack](https://gist.github.com/a-rodin/fef3f543412d6e1ec5b6cf55bf197d7b). See the markdown comment at the beginning of the encoding section.

docs: Add docs/sat-solver.md with justification

---

cmd/hypper/install_test.go

Fixing location of repo cache and config in install tests
